### ISSUE TITLE
Questions related to permalink, post pagination

### ISSUE THREAD

**Issue by ckunte** [semk/voldemort#6]
Hi Sreejith: Voldermort looks like a good piece of work; many congratulations. I stumbled on your repo., while looking for a way to add post pagination to a [chisel fork][cf] that I currently use. I would be grateful for any suggestions/advice in this regard. (Apologies for this somewhat off-topic question.)

I also looked at using Voldermort natively for my site, but I seem to have a preference for URLs ending without the `/`. Currently, I generate posts with `.html`, but are linked without the `.html` part (this works fine on github due to (nginx) server side directive at github). Is there any way to set a preference for such/similar permalinks in Voldermort?

[cf]: https://gist.github.com/ckunte/2c50a783c09c3bb893c4

**Comment by semk** [comment]
Hi Chyetanya,

Thanks for the feedback. Currently the option you are looking for is not configurable externally using the settings file. I will probably work on it when I get free time and update here.
